# Generated by Django 6.0.5 on 2026-06-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('idAlbum', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fechaLanzamiento', models.DateField()),
                ('imagen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '[Catalogo].[Album]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.AutoField(primary_key=True, serialize=False)),
                ('nombreArtistico', models.CharField(db_column='nombre', max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('imagen', models.CharField(default='default_artist.png', max_length=255)),
                ('biografia', models.CharField(max_length=500)),
            ],
            options={
                'db_table': '[Catalogo].[Artista]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('idCancion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('numeroPista', models.IntegerField()),
                ('fechaLanzamiento', models.DateField()),
                ('calidadAudio', models.CharField(default='Alta', max_length=20)),
                ('imagen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '[Catalogo].[Cancion]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CancionGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '[Catalogo].[CancionGenero]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discografica',
            fields=[
                ('idDiscografica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('fechaFundacion', models.DateField()),
                ('logo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '[Catalogo].[Discografica]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '[Catalogo].[Genero]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': '[Usuarios].[Notificacion]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEntity',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Free', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracionDias', models.IntegerField()),
            ],
            options={
                'db_table': '[Facturacion].[PlanEntity]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('idPlaylist', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField()),
                ('privacidad', models.CharField(default='Privada', max_length=15)),
                ('descripcion', models.CharField(max_length=255)),
                ('colaborativa', models.BooleanField()),
            ],
            options={
                'db_table': '[Usuarios].[Playlist]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAgregada', models.DateField()),
            ],
            options={
                'db_table': '[Usuarios].[PlaylistCancion]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('idReproduccion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('dispositivo', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('duracionEscuchada', models.IntegerField()),
                ('completada', models.BooleanField()),
            ],
            options={
                'db_table': '[Usuarios].[Reproduccion]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': '[Usuarios].[Rol]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('idSuscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(default='Inactiva', max_length=15)),
            ],
            options={
                'db_table': '[Facturacion].[Suscripcion]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioAlbum',
            fields=[
                ('Usuario_idUsuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.usuario')),
            ],
            options={
                'db_table': '[Usuarios].[UsuarioAlbum]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('Usuario_idUsuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.usuario')),
                ('fechaSeguimiento', models.DateField()),
            ],
            options={
                'db_table': '[Usuarios].[UsuarioArtista]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCancion',
            fields=[
                ('Usuario_idUsuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registros.usuario')),
                ('fechaAgregada', models.DateField()),
            ],
            options={
                'db_table': '[Usuarios].[UsuarioCancion]',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
